import { Ajv } from 'ajv';
import ajvFormats from 'ajv-formats';
import { SCRIPT_SCHEMA } from './script-schema';

const ajv = new Ajv();
ajvFormats(ajv);

/**
 * A compiled validation function generated by the AJV library based on the provided SCRIPT_SCHEMA.
 * This function can be used to validate JavaScript objects against the predefined schema.
 */
export const isValidScript = ajv.compile(SCRIPT_SCHEMA);
