import { Ajv } from 'ajv';
import ajvFormats from 'ajv-formats';
import { COMIC_RACK_SCRIPT_SCHEMA } from './script-schema';

const ajv = new Ajv({
	allErrors: true
});
ajvFormats(ajv);

/**
 * A compiled validation function generated by the AJV library based on the provided SCRIPT_SCHEMA.
 * This function can be used to validate JavaScript objects against the predefined schema.
 */
export const isValidScript = ajv.compile(COMIC_RACK_SCRIPT_SCHEMA);
