name: Run Checks

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install
        run: npm install

      - name: Validate
        run: npm run validate:scripts

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Check
        run: npm run check
